name: zypt
description: "ZyptoPulse - Crypto Tracking App"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^8.1.0
  http: ^0.13.6
  shared_preferences: ^2.2.2
  go_router: ^12.0.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
